// Ground-truth tessellation generator for the tess2-rust conformance test.
//
// Reads the classic AGG lion polygon set from `tests/data/lion.txt`, runs
// **MatterCAD's agg-sharp Tesselator** (the same C# libtess2 port that
// drives MatterCAD's full design tool) over every polygon, and writes the
// resulting vertex list, triangle indices, and per-index edge-flags to a
// deterministic text file.  The Rust integration test
// `tests/conformance_vs_csharp.rs` then loads that file and asserts that
// `tess2-rust` reproduces it numerically.
//
// Output format (one block per input polygon; blocks separated by blank
// lines).  `V` lines are `"V <index> <x> <y>"` with doubles printed at
// full G17 precision so they round-trip through `f64::parse`.  `I` lines
// are `"I <vertex_index> <edge_flag_0_or_1>"` listing every triangle
// vertex in the order tess2 emitted it (triples = triangles).
//
//   POLY <polygon_index> <input_vertex_count>
//   V <i> <x> <y>
//   V <i> <x> <y>
//   ...
//   I <v> <f>
//   I <v> <f>
//   I <v> <f>
//   ...

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Tesselate;

// Minimal copy of MatterCAD's `CachedTesselator` — inlined here to avoid
// pulling in the whole `DataConverters2D` project (which transitively needs
// Agg, clipper, VectorMath etc).  The behaviour is byte-identical to the
// upstream class.
sealed class CachedTess : Tesselator
{
    public sealed class AddedVertex
    {
        public double X;
        public double Y;
        public AddedVertex(double x, double y) { X = x; Y = y; }
    }
    public sealed class RenderIndex
    {
        public int Index;
        public bool IsEdge;
        public RenderIndex(int i, bool e) { Index = i; IsEdge = e; }
    }

    public readonly List<AddedVertex> VerticesCache = new();
    public readonly List<RenderIndex> IndicesCache = new();
    private bool lastEdgeFlag = false;

    public CachedTess()
    {
        callVertex    = VertexCallBack;
        callEdgeFlag  = EdgeFlagCallBack;
        callCombine   = CombineCallBack;
    }

    public override void BeginPolygon()
    {
        VerticesCache.Clear();
        IndicesCache.Clear();
        base.BeginPolygon();
    }

    private void VertexCallBack(int index)
    {
        IndicesCache.Add(new RenderIndex(index, lastEdgeFlag));
    }

    private void EdgeFlagCallBack(bool isEdge)
    {
        lastEdgeFlag = isEdge;
    }

    private int CombineCallBack(double[] coords3, int[] data4, double[] weight4)
    {
        return AddVertexDirect(coords3[0], coords3[1], false);
    }

    public void AddVertex(double x, double y)
    {
        AddVertexDirect(x, y, true);
    }

    private int AddVertexDirect(double x, double y, bool passOn)
    {
        int idx = VerticesCache.Count;
        VerticesCache.Add(new AddedVertex(x, y));
        if (passOn)
        {
            var coords = new double[2] { x, y };
            AddVertex(coords, idx);
        }
        return idx;
    }
}

static class Program
{
    // Enough decimal digits that the value round-trips through `f64::parse`
    // with zero loss — this is the invariant the conformance test relies on.
    static string F(double v) => v.ToString("G17", CultureInfo.InvariantCulture);

    static void Main(string[] args)
    {
        string toolsDir = AppContext.BaseDirectory;
        // Walk up from `bin/Debug/net9.0/` to `tools/LionReferenceGen/`, then
        // `tools/`, then the tess2-rust root.
        string repoRoot = Path.GetFullPath(Path.Combine(toolsDir, "..", "..", "..", "..", ".."));
        string lionPath = args.Length >= 1
            ? args[0]
            : Path.Combine(repoRoot, "tests", "data", "lion.txt");
        string outPath  = args.Length >= 2
            ? args[1]
            : Path.Combine(repoRoot, "tests", "data", "lion_tess_reference.txt");

        Console.WriteLine($"Reading  {lionPath}");
        Console.WriteLine($"Writing  {outPath}");

        var polygons = ParseLion(File.ReadAllLines(lionPath));
        Console.WriteLine($"{polygons.Count} polygon(s) parsed");

        using var writer = new StreamWriter(outPath);
        writer.WriteLine("# tess2-rust conformance reference — generated by LionReferenceGen");
        writer.WriteLine("# Source: MatterCAD agg-sharp Tesselator (C# port of libtess2).");
        writer.WriteLine("# Winding rule: Odd (matches tess2-rust default for lion polygons).");
        writer.WriteLine();

        for (int i = 0; i < polygons.Count; i++)
        {
            var poly = polygons[i];
            var tess = BuildCachingTesselator();
            try
            {
                tess.BeginPolygon();
                tess.BeginContour();
                foreach (var (x, y) in poly)
                {
                    tess.AddVertex(x, y);
                }
                tess.EndContour();
                tess.EndPolygon();
            }
            catch (Exception e)
            {
                Console.Error.WriteLine($"polygon {i}: agg-sharp threw {e.GetType().Name}: {e.Message}");
                continue;
            }

            writer.WriteLine($"POLY {i} {poly.Count}");
            for (int v = 0; v < tess.VerticesCache.Count; v++)
            {
                var av = tess.VerticesCache[v];
                writer.WriteLine($"V {v} {F(av.X)} {F(av.Y)}");
            }
            foreach (var idx in tess.IndicesCache)
            {
                writer.WriteLine($"I {idx.Index} {(idx.IsEdge ? 1 : 0)}");
            }
            writer.WriteLine();
        }

        Console.WriteLine("done");
    }

    static CachedTess BuildCachingTesselator()
    {
        var tess = new CachedTess();
        tess.windingRule = Tesselator.WindingRuleType.Odd;
        return tess;
    }

    // Parse the lion data file: colour lines are hex RRGGBB, path lines
    // start with `M` and contain `x,y` coordinate pairs separated by `L`.
    // Each `M…L…` line is a sub-polygon; strip the trailing duplicate
    // closing run.
    static List<List<(double X, double Y)>> ParseLion(string[] rawLines)
    {
        var polys = new List<List<(double X, double Y)>>();
        foreach (var raw in rawLines)
        {
            string line = raw.Trim();
            if (line.Length == 0) continue;
            if (line.Length == 6 && IsHex(line)) continue;
            if (!line.StartsWith("M")) continue;

            var verts = new List<(double X, double Y)>();
            foreach (var tok in line.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries))
            {
                if (tok == "M" || tok == "L") continue;
                var parts = tok.Split(',');
                if (parts.Length != 2) continue;
                if (!double.TryParse(parts[0], NumberStyles.Float, CultureInfo.InvariantCulture, out double x)) continue;
                if (!double.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out double y)) continue;
                verts.Add((x, y));
            }
            while (verts.Count >= 2 && verts[^1].Equals(verts[^2]))
                verts.RemoveAt(verts.Count - 1);
            // Also strip the trailing first-last closing duplicate — the
            // Rust tess2 auto-merges these during `remove_degenerate_edges`,
            // so we pre-strip on input to keep vertex counts comparable.
            if (verts.Count >= 2 && verts[^1].Equals(verts[0]))
                verts.RemoveAt(verts.Count - 1);
            if (verts.Count >= 3) polys.Add(verts);
        }
        return polys;
    }

    static bool IsHex(string s)
    {
        foreach (char c in s)
        {
            if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')))
                return false;
        }
        return true;
    }
}
